require_relative './config/environment'
require 'sinatra/activerecord/rake'

desc "Start our app console"
task :console do
  # enables logging in Pry console whenever Active Record writes SQL for us
  ActiveRecord::Base.logger = Logger.new(STDOUT)
  # open Pry console, similar to binding.pry
  Pry.start
end


desc "Print out lots of emojis"
task :print_emojis do
  puts "🏄‍♀️🏌️‍♀️🤾🧘‍♀️🏋️‍♀️" * 5000
end